### ISSUE TITLE
data driven for class fields

### ISSUE THREAD

**Issue by SiKing** [EaseTech/easytest-core#132]
I would like to be able to do something like:

```
@RunWith(DataDrivenTestRunner.class)
@DataLoader(filePaths = { "/testData.csv" }, loaderType = LoaderType.CSV)
public class SampleTest {

	private double data;

	public SampleTest(@Param(name = "data") String data) {
		this.data = Double.parseDouble(data);
	}

	@Test
	public void test() {
		System.out.println("Run: " + data);
	}
}
```

testData.csv (as a _guess_) contains:

```
SampleTest,data
 ,1
 ,2
```

What I am going for is that the entire class, all tests, will be run once for each entry in my testData.

Currently I only get:

```
java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.easetech.easytest.runner.DataDrivenTestRunner.createTest(DataDrivenTestRunner.java:377)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.easetech.easytest.runner.DataDrivenTestRunner.methodBlock(DataDrivenTestRunner.java:340)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.easetech.easytest.strategy.SerialScheduler.schedule(SerialScheduler.java:16)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.easetech.easytest.util.RunAftersWithOutputData.evaluate(RunAftersWithOutputData.java:111)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by anujgandharv** [comment]
Hi SiKing, 
 Sorry but that is not possible with EasyTest. This limitation is mostly to do with the fact that EasyTest is essentially an extension of JUnit which does not allow such a functionality to be implemented in an easy manner.

But if you are able to extend EasyTest with such a functionality, I would be more than happy to include it.

Thanks,
Anuj Kumar

**Comment by SiKing** [comment]
Bummer. I will see if I can come up with a workaround. Not sure about enhancing EasyTest - I am not that good. :cry:
