### ISSUE TITLE
Nullpointer exception when running easytest

### ISSUE THREAD

**Issue by RamnathRaghu** [EaseTech/easytest-core#134]
Hi 

I am seeing the below error. Please help me understand what is it about and how to get rid of this?

code:

@RunWith(DataDrivenTestRunner.class)
@DataLoader(filePaths={"C:\\Desktop\\easytestdata.xls"} , loaderType=LoaderType.EXCEL)
public class SampleClass{
	

	@Test
	public void runtest(@Param(name = "Environment")Map<String, String> environment ) throws Exception {
//		String xmlFilesFolderPath = TestTrigger.runTest();
		out.println("Environment is " + environment);
		fail("Not yet implemented");
	}

_______________________________

java.lang.NullPointerException
	at org.easetech.easytest.util.GeneralUtil.dataAlreadyConverted(GeneralUtil.java:537)
	at org.easetech.easytest.converter.DataAlreadyConvertedConverter.convert(DataAlreadyConvertedConverter.java:67)
	at org.easetech.easytest.converter.DataAlreadyConvertedConverter.convert(DataAlreadyConvertedConverter.java:22)
	at org.easetech.easytest.converter.ConversionDelegator.convert(ConversionDelegator.java:127)
	at org.easetech.easytest.annotation.Param$DataSupplier.getValueSources(Param.java:196)
	at org.easetech.easytest.internal.EasyAssignments.potentialsForNextUnassigned(EasyAssignments.java:100)
	at org.easetech.easytest.runner.InternalParameterizedStatement.runWithAssignment(InternalParameterizedStatement.java:116)
	at org.easetech.easytest.runner.InternalParameterizedStatement.evaluate(InternalParameterizedStatement.java:99)
	at org.easetech.easytest.runner.DataDrivenTestRunner$1.evaluate(DataDrivenTestRunner.java:350)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.easetech.easytest.strategy.SerialScheduler.schedule(SerialScheduler.java:16)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.easetech.easytest.util.RunAftersWithOutputData.evaluate(RunAftersWithOutputData.java:111)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by RamnathRaghu** [comment]
This is resolved. the letters case of the test method name did not match that of the one in the code. Hence closing this.

**Comment by thiagopaschoal** [comment]
I tried to solve this problem with the Ram-Raghu's answered, but without sucess. There is a other to solve this problem?

**Comment by anujgandharv** [comment]
Hi thiago. Can you share your test code that has issue. I will look into ot

**Comment by thiagopaschoal** [comment]
Hey man!! Thanks for your attention, but I solved this problem. The error was during the csv file creation. So, I have one question. How to use easytest with springboot? There is some example to send to me?

**Comment by fabianaCarvalhoCea** [comment]
Hi, Thiago I found this the same problem, could you to share your solution, please?
